# Generated by Django 4.2.1 on 2023-05-14 11:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Администрация')),
                ('confirmed_email', models.BooleanField(default=False, verbose_name='Подтвержденная почта')),
                ('first_name', models.CharField(max_length=31, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=31, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=31, null=True, verbose_name='Отчество')),
                ('sex', models.CharField(blank=True, choices=[('ML', 'Мужчина'), ('FM', 'Женщина')], max_length=2, null=True)),
                ('about', models.TextField(blank=True, max_length=2000, null=True, verbose_name='О себе')),
                ('groups', models.ManyToManyField(related_name='myapp_users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='app_users', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Реестр пользователей',
            },
        ),
    ]
